services:
  - type: web
    name: api-node-ts
    env: node
    region: oregon    
    plan: free

    buildCommand: npm install && npm run build
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  

    autoDeploy: true
